#!/bin/sh

case "$1" in
	start)
		/bin/start-stop-daemon -S -b -n netflix-pbrd -x /opt/sbin/netflix-pbrd -- -config /opt/etc/netflix-pbrd.json
		;;
	restart|reconfigure)
		/bin/start-stop-daemon -K -n netflix-pbrd >/dev/null 2>&1 || true
		/bin/start-stop-daemon -S -b -n netflix-pbrd -x /opt/sbin/netflix-pbrd -- -config /opt/etc/netflix-pbrd.json
		;;
  stop|kill)
    /bin/start-stop-daemon -K -n netflix-pbrd
    ;;
esac

return 0 2>/dev/null || exit 0
