#!/bin/sh

PIDFILE=/opt/var/run/netflix-pbrd.pid

case "$1" in
	start)
		/bin/start-stop-daemon -S -b -m -p "$PIDFILE" -x /opt/sbin/netflix-pbrd -- -config /opt/etc/netflix-pbrd.json
		;;
	restart|reconfigure)
		/bin/start-stop-daemon -K -p "$PIDFILE" >/dev/null 2>&1 || true
		rm -f "$PIDFILE"
		/bin/start-stop-daemon -S -b -m -p "$PIDFILE" -x /opt/sbin/netflix-pbrd -- -config /opt/etc/netflix-pbrd.json
		;;
  stop|kill)
		/bin/start-stop-daemon -K -p "$PIDFILE" || true
		rm -f "$PIDFILE"
    ;;
esac

return 0 2>/dev/null || exit 0
